"""Temporal activity recognition contracts: ActionObservation & ConfirmedAction."""

from __future__ import annotations

from typing import Any
from pydantic import BaseModel, ConfigDict, Field
from astra.contracts.base import BaseMessage, current_timestamp


class TemporalWindow(BaseModel):
    """Observation interval over which the action was inferred."""
    model_config = ConfigDict(frozen=True)

    start: float = Field(description="Start timestamp in seconds")
    end: float = Field(description="End timestamp in seconds")


class ActionObservation(BaseMessage):
    """
    Contract 04: ActionObservation.
    Probabilistic output from temporal ML models (LSTM/TCN/Transformer).
    Signifies: 'The AI model believes this action is occurring.'
    """
    action: str = Field(description="Action identifier, e.g. PICK, PLACE, OPEN_CONTAINER")
    actor_id: str = Field(default="astronaut", description="Actor performing action")
    object_id: str | None = Field(default=None, description="Object involved, e.g. RED_COMPONENT")
    target_id: str | None = Field(default=None, description="Destination target, e.g. TARGET_A")
    confidence: float = Field(ge=0.0, le=1.0, description="Inference confidence score")
    event_time: float = Field(default_factory=current_timestamp, description="Timestamp of physical activity")
    temporal_window: TemporalWindow | None = Field(default=None)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ConfirmationMetadata(BaseModel):
    """Evidence metrics generated by the Confidence/Confirmation layer."""
    model_config = ConfigDict(frozen=True)

    stable_frames: int = Field(ge=1, description="Number of consecutive coherent frames")
    minimum_confidence: float = Field(ge=0.0, le=1.0, description="Lowest confidence within confirmation window")
    temporal_consistency: float = Field(ge=0.0, le=1.0, description="Consistency score across sliding window")


class ConfirmedAction(BaseMessage):
    """
    Contract 05: ConfirmedAction.
    Produced by the confirmation layer after temporal smoothing and hysteresis filtering.
    Only confirmed actions are dispatched to the deterministic Procedure Engine.
    """
    action: str = Field(description="Confirmed semantic action verb")
    actor_id: str = Field(default="astronaut", description="Actor identifier")
    object_id: str | None = Field(default=None, description="Object involved, e.g. RED_COMPONENT")
    target_id: str | None = Field(default=None, description="Target location, e.g. TARGET_A")
    confidence: float = Field(ge=0.0, le=1.0, description="Calibrated confidence")
    event_time: float = Field(default_factory=current_timestamp, description="Action timestamp")
    confirmation: ConfirmationMetadata | None = Field(default=None)
